// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAofgk3kbG31WnmpBwkfGGKOq287Z1Bx-I',
    appId: '1:274153695789:web:a3ba66f75cd349a714e6a4',
    messagingSenderId: '274153695789',
    projectId: 'ai-training-3e784',
    authDomain: 'ai-training-3e784.firebaseapp.com',
    storageBucket: 'ai-training-3e784.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqsr8HYNuHFqdVD9RSweGqvbg6f_LP2Jg',
    appId: '1:274153695789:android:d1e4bbaf35754c6b14e6a4',
    messagingSenderId: '274153695789',
    projectId: 'ai-training-3e784',
    storageBucket: 'ai-training-3e784.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw9VsOm_ERQvrmVDTwTTZ5mcMl1R2R8UM',
    appId: '1:274153695789:ios:8554582aa0736b2314e6a4',
    messagingSenderId: '274153695789',
    projectId: 'ai-training-3e784',
    storageBucket: 'ai-training-3e784.firebasestorage.app',
    iosBundleId: 'com.example.aiTraining',
  );
}
